name: Build ZMK firmware
on:
  workflow_dispatch: # can be triggered manually
  push:
    branches-ignore: [main]
    paths: ["config/*.keymap"]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
